#!/bin/sh

ln -s ${SYNOPKG_PKGDEST}/app /usr/syno/synoman/webman/3rdparty/MediaAdapter
mkdir -p ${SYNOPKG_PKGDEST}/lib ${SYNOPKG_PKGDEST}/var/tmp ${SYNOPKG_PKGDEST}/var/log ${SYNOPKG_PKGDEST}/var/run
chown -R admin.users ${SYNOPKG_PKGDEST}
exit 0 
