#!/bin/sh

if [ -z ${JAVA_HOME} ]; then
    echo "Java is not configured. JAVA_HOME is not defined." > $SYNOPKG_TEMP_LOGFILE
    exit 1
fi

if [ ! -f ${JAVA_HOME}/bin/java ]; then
    echo "Java is not configured. Could not find Java binary." > $SYNOPKG_TEMP_LOGFILE
    exit 1
fi

exit 0
